### ISSUE TITLE
Download functionality from service workers failing

### ISSUE THREAD

**Issue by ishaanv** [bkhpanigha/hh-suttas#108]
Haven't got a chance to deep dive into the issue, but it seems quite a few of the sutta files are failing to download when the "Download" button is clicked

![image](https://github.com/bkhpanigha/hh-suttas/assets/4453276/ddeef6b8-6953-4b12-a414-15129d35887b)

**Comment by Reptilioo** [comment]
I came up with a system caching files by batch so as to not get the failed fetch because too much resources were pulled at once, but I'm not sure it will work with every browser/computer configuration/internet speed.
It can take from 20secs to 1min to cache all files.

And I've noticed it sometimes downloads file indefinitly.

https://github.com/Reptilioo/hh-suttas/blob/2f47fda633fd0a3da4300b00d7e1cf5c6df4ce78/sw.js
#

**Comment by Reptilioo** [comment]
Also I noticed the page always need to be reloaded at least once after the Service Worker get registered and installed in order to be able to cache the files, maybe there is a way to make it work as soon as it is registered and installed

**Comment by Reptilioo** [comment]
I think the issue comes from the fact that now there is 8000+ files that are downloaded compared to 600+ not so long ago, and probably comes from the modifications I made on sutta_catalog_manager.py, will check that later.

Also will probably include a way to download files in batches so we don't face the same issue later on when we will have a lot of content to fetch.
