### ISSUE TITLE
Offline mode not working 

### ISSUE THREAD

**Issue by uruvelakassapa** [bkhpanigha/hh-suttas#176]
Might just be me but the suttas don't load with the current version when offline

**Comment by Reptilioo** [comment]
The issue is coming from the fact the Dexie is downloaded from a distant server: https://github.com/bkhpanigha/hh-suttas/blob/7b3494f9aadc5b36b1924007e7b42f471a7b354f/index.html#L21

The issue is resolved if we download [this file](https://unpkg.com/dexie@4.0.8/dist/dexie.js) somewhere like "/js/dexie/dist/dexie.js".

Do you see any issue with that? Importing it from a distant server is good in case there are updates but in our case I'm not sure it's problematic.

**Comment by uruvelakassapa** [comment]
Thanks for looking into that. Downloading it locally makes sense to me. I did the same for fuse.js when we were using it.
